options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install. May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Ubuntu Cloud Archive e.g.
      .
      cloud:<series>-<openstack-release>
      cloud:<series>-<openstack-release>/updates
      cloud:<series>-<openstack-release>/staging
      cloud:<series>-<openstack-release>/proposed
      .
      See https://wiki.ubuntu.com/OpenStack/CloudArchive for info on which
      cloud archives are available and supported.
  rabbit-user:
    default: ironic
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  database-user:
    default: ironic
    type: string
    description: Username for Magnum database access
  database:
    default: ironic
    type: string
    description: Database name for Magnum
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  use-ipxe:
    default: false
    type: boolean
    description: |
      Use iPXE instead of PXE. This option will install an aditional
      HTTP server with a root in /httpboot.
  ipxe-http-port:
    default: "8080"
    type: string
    description: |
      The port used for the HTTP server used to serve iPXE resources.
  api-port:
    default: "6385"
    type: string
    description: |
      The API port ironic-api will listen on.
  max-tftp-block-size:
    default: 0
    type: integer
    description: |
      The maximum block size to use in the TFTP server. Setting this option
      to anything other than 0, will force the block size sent over TFTP to
      the value specified here. Valid range is 512-65535. By default, clients
      will negotiate the block size.

      Use this option if you're running ironic in a network with lower
      MTU. The value of this option should be 32 bits less than the MTU.
      If your MTU is 1450, the value for this option should be 1418.

  